### ISSUE TITLE
Vector widths in matmul code and data dependencies

### ISSUE THREAD

**Issue by cgbur** [clebert/llama2.zig#1]
I think the vector widths you are using are too large. 32x4 is 128 bytes or 1024 bits which is much larger than the width of any vector type that is on cpus today. 

`std.simd.suggestVectorSize(f32) ` will return the current cpus maximum vector size for a given type. I think seeing an improvement by making it larger means something else is going on that is not related.

Also there is performance to be had from reworking your summing by using a vector of sums. Currently the CPU struggles to optimize because of a data dependency as each sum needs to depend on the previous lanes value. If you instead keep N sums and then reduce them at the end you should see a speedup.
```zig
var value: @Vector(v_len, f32) = @splat(0.0);
... loop
value += a * b;
...
xoutptr.* = @reduce(.Add, value);
```

**Comment by clebert** [comment]
The native size of my CPU is 4 (128 bits). The Zig documentation states the following:

> Operations on vectors shorter than the target machine's native SIMD size will typically compile to
> single SIMD instructions, while vectors longer than the target machine's native SIMD size will
> compile to multiple SIMD instructions.

When I ran benchmarks, optimal performance appeared to be at a length of 16. Interestingly, the
performance improvement you suggested (cutting down the number of `@reduce` calls) seemed to produce
better results only with smaller vector sizes.

I turned the output off and cherry-picked the best result out of 3 runs. I also kept the temperature
at 0 to ensure the results were not skewed.

**Build:** `zig build -Doptimize=ReleaseFast`

**Run:** `./zig-out/bin/llama2 stories15M.bin -t 0.0 -n 256`

|           | len=4   | len=8   | len=16  | len=32  |
| --------- | ------- | ------- | ------- | ------- |
| main      | 373 t/s | 600 t/s | 632 t/s | 629 t/s |
| optimized | 405 t/s | 617 t/s | 632 t/s | 632 t/s |

**Run:** `./zig-out/bin/llama2 stories110M.bin -t 0.0 -n 256`

|           | len=4  | len=8  | len=16  | len=32  |
| --------- | ------ | ------ | ------- | ------- |
| main      | 46 t/s | 84 t/s | 102 t/s | 100 t/s |
| optimized | 51 t/s | 86 t/s | 102 t/s | 100 t/s |

Based on the test results, it currently seems best if I adopt your proposed optimization and set the
vector length to 16. However, it's not entirely clear to me why exactly four times the size of the
native vector size appears to be optimal.

Appreciate your time and thoughts!

**Comment by cgbur** [comment]
Thats really odd! I also see the same thing with your code.

| len=4| len=8 | len=16| len=32 | len=64
|--|--| --| --| --| 
| 398|469| 480 | 504| 483| 

Interestingly I actually found that in my code the opposite is true?

| len=4| len=8 | len=16| len=32 | len=64
|--|--| --| --| --| 
| 602|606| 601 | 503| 343| 

My matmul https://github.com/cgbur/llama2.zig/blob/eb282fd39a61a18149b26bfed5cb80c2ce482c3c/src/main.zig#L495

I am thinking that mine is more unfriendly to the stack so the bigger unrolls hurt more. Need to do more investigating
