### ISSUE TITLE
Running with -t 0 error

### ISSUE THREAD

**Issue by cgbur** [clebert/llama2.zig#2]
Running with just checkpoint and -t 0 procudes
```sh
❯ zig-out/bin/llama2 stories15M.bin -t 0
Error: To control the diversity of samples use either the temperat
ure or the top-p value, but not both.

Usage: llama2 <checkpoint_path> [options]

Options:
  -t <float>  temperature  = 1
  -p <float>  top_p        = 0.9; 0 == off
  -s <int>    random_seed  = milli_timestamp
  -n <int>    n_steps      = 256; 0 == max_seq_len
  -i <string> input_prompt = ""

Example: llama2 model.bin -i "Once upon a time"
```

Also I dont think there is anything wrong with using temperature and top p together.

**Comment by clebert** [comment]
Generally, I read in both Andrej's README and for example at OpenAI API docs: We generally recommend altering temperature or top_p but not both.

But maybe I've interpreted that too strictly.

**Comment by cgbur** [comment]
Got it I didn’t realize that. I followed the llama c code which applies it both. This issue was mostly that it currently errors out when just passing -t 0.
